export const circuits = [
  {
    id: 'monaco',
    name: 'Circuit de Monaco',
    locality: 'Monte Carlo',
    country: 'Monaco',
    lat: 43.7347,
    lon: 7.4206,
    laps: 78,
    lengthKm: 3.337,
    fact: {
      en: 'The slowest and most demanding circuit on the calendar - barely wide enough for two cars side by side.',
      ka: 'კალენდარის ყველაზე ნელი და მოთხოვნადი ტრასა - სივრცე ძლივს ჰყოფნის ორ მანქანას გვერდიგვერდ.',
    },
  },
  {
    id: 'monza',
    name: 'Autodromo Nazionale Monza',
    locality: 'Monza',
    country: 'Italy',
    lat: 45.6156,
    lon: 9.2811,
    laps: 53,
    lengthKm: 5.793,
    fact: {
      en: 'Nicknamed the "Temple of Speed" - the lowest-downforce, highest top-speed track of the season.',
      ka: '"სიჩქარის ტაძრის" მეტსახელით - სეზონის ყველაზე მაღალი მაქსიმალური სიჩქარის ტრასა.',
    },
  },
  {
    id: 'silverstone',
    name: 'Silverstone Circuit',
    locality: 'Silverstone',
    country: 'United Kingdom',
    lat: 52.0786,
    lon: -1.0169,
    laps: 52,
    lengthKm: 5.891,
    fact: {
      en: 'Built on a WWII airfield and hosted the very first Formula 1 World Championship race in 1950.',
      ka: 'მეორე მსოფლიო ომის აეროდრომზე აშენდა და 1950 წელს უმასპინძლა ფორმულა 1-ის პირველივე ჩემპიონატის რბოლას.',
    },
  },
  {
    id: 'spa',
    name: 'Circuit de Spa-Francorchamps',
    locality: 'Stavelot',
    country: 'Belgium',
    lat: 50.4372,
    lon: 5.9714,
    laps: 44,
    lengthKm: 7.004,
    fact: {
      en: 'Famous for Eau Rouge / Raidillon - a blind, uphill compression that drivers take at full throttle.',
      ka: 'ცნობილია Eau Rouge / Raidillon-ით - ბრმა, აღმავალი მონაკვეთი, რომელსაც მძღოლები სრულ გაზზე გადიან.',
    },
  },
  {
    id: 'suzuka',
    name: 'Suzuka International Racing Course',
    locality: 'Suzuka',
    country: 'Japan',
    lat: 34.8431,
    lon: 136.5410,
    laps: 53,
    lengthKm: 5.807,
    fact: {
      en: 'One of the only figure-eight circuits in motorsport, with the track crossing over itself.',
      ka: 'ერთ-ერთი იშვიათი "8" ფორმის ტრასაა მოტოსპორტში - ტრასა საკუთარ თავს კვეთს.',
    },
  },
  {
    id: 'interlagos',
    name: 'Autódromo José Carlos Pace',
    locality: 'São Paulo',
    country: 'Brazil',
    lat: -23.7036,
    lon: -46.6997,
    laps: 71,
    lengthKm: 4.309,
    fact: {
      en: 'Run anticlockwise, with a steep elevation change between the start/finish straight and the infield.',
      ka: 'საათის ისრის საწინააღმდეგო მიმართულებით - სტარტის სვეტისა და ტრასის შინაგან ნაწილს შორის დიდი ფერდობია.',
    },
  },
  {
    id: 'marina_bay',
    name: 'Marina Bay Street Circuit',
    locality: 'Singapore',
    country: 'Singapore',
    lat: 1.2914,
    lon: 103.8640,
    laps: 62,
    lengthKm: 4.940,
    fact: {
      en: "F1's first night race under floodlights, run on city streets around Marina Bay.",
      ka: 'ფორმულა 1-ის პირველი ღამის რბოლა, რომელიც ქალაქის ქუჩებში, Marina Bay-ს გარშემო იმართება.',
    },
  },
  {
    id: 'cota',
    name: 'Circuit of the Americas',
    locality: 'Austin',
    country: 'United States',
    lat: 30.1328,
    lon: -97.6411,
    laps: 56,
    lengthKm: 5.513,
    fact: {
      en: 'Turn 1 climbs 41 metres in under 200 metres - one of the steepest opening corners in F1.',
      ka: '1-ელი ვირაჯი 200 მეტრზე ნაკლებში 41 მეტრით აღმავალია - ერთ-ერთი ყველაზე ციცაბო საწყისი ვირაჯი F1-ში.',
    },
  },
];

export const getCircuitById = (id) => circuits.find((c) => c.id === id);
