import axiosInstance from "./axiosInstance";
import { teams } from "./teamsData";

// API-დან გუნდის ფერები არ მოდის, ამიტომ აქ გვაქვს გაწერილი ხელით
const TEAM_COLORS = {
  red_bull: teams.red_bull.color,
  ferrari: teams.ferrari.color,
  mercedes: teams.mercedes.color,
  mclaren: teams.mclaren.color,
  aston_martin: teams.aston_martin.color,
  alpine: teams.alpine.color,
  williams: teams.williams.color,
  haas: teams.haas.color,
  audi: teams.audi.color,
  cadillac: teams.cadillac.color,
  rb: teams.rb.color,
  surprise: teams.surprise.color,
  default: "#8A929B",
};

const FALLBACK_DRIVERS = [
  {
    id: "driver-1",
    code: "SCR",
    name: "Scarlet Racer",
    team: "Apex Bulls",
    teamKey: "red_bull",
    nationality: "Dutch",
    color: TEAM_COLORS.red_bull,
    points: 312,
    wins: 6,
    position: 1,
  },
  {
    id: "driver-2",
    code: "ENB",
    name: "Energy Bolt",
    team: "Apex Bulls",
    teamKey: "red_bull",
    nationality: "Mexican",
    color: TEAM_COLORS.red_bull,
    points: 187,
    wins: 1,
    position: 6,
  },
  {
    id: "driver-3",
    code: "PAP",
    name: "Papaya Dash",
    team: "Scuderia Rosso",
    teamKey: "ferrari",
    nationality: "Monégasque",
    color: TEAM_COLORS.ferrari,
    points: 268,
    wins: 3,
    position: 2,
  },
  {
    id: "driver-4",
    code: "GLD",
    name: "Golden Pitstop",
    team: "Scuderia Rosso",
    teamKey: "ferrari",
    nationality: "Spanish",
    color: TEAM_COLORS.ferrari,
    points: 231,
    wins: 2,
    position: 4,
  },
  {
    id: "driver-5",
    code: "SLV",
    name: "Silver Arrow",
    team: "Silver Star",
    teamKey: "mercedes",
    nationality: "British",
    color: TEAM_COLORS.mercedes,
    points: 241,
    wins: 2,
    position: 3,
  },
  {
    id: "driver-6",
    code: "CHM",
    name: "Crystal Champion",
    team: "Silver Star",
    teamKey: "mercedes",
    nationality: "British",
    color: TEAM_COLORS.mercedes,
    points: 176,
    wins: 0,
    position: 7,
  },
  {
    id: "driver-7",
    code: "AZC",
    name: "Azure Comet",
    team: "Papaya Works",
    teamKey: "mclaren",
    nationality: "Australian",
    color: TEAM_COLORS.mclaren,
    points: 219,
    wins: 2,
    position: 5,
  },
  {
    id: "driver-8",
    code: "SUN",
    name: "Sunset Turbo",
    team: "Papaya Works",
    teamKey: "mclaren",
    nationality: "Brazilian",
    color: TEAM_COLORS.mclaren,
    points: 198,
    wins: 1,
    position: 8,
  },
  {
    id: "driver-9",
    code: "EMD",
    name: "Emerald Drift",
    team: "Green Martin",
    teamKey: "aston_martin",
    nationality: "Spanish",
    color: TEAM_COLORS.aston_martin,
    points: 154,
    wins: 0,
    position: 9,
  },
  {
    id: "driver-10",
    code: "PNK",
    name: "Pink Bloom",
    team: "Green Martin",
    teamKey: "aston_martin",
    nationality: "Canadian",
    color: TEAM_COLORS.aston_martin,
    points: 89,
    wins: 0,
    position: 12,
  },
  {
    id: "driver-11",
    code: "VIO",
    name: "Violet Velocity",
    team: "Blue Alpinia",
    teamKey: "alpine",
    nationality: "French",
    color: TEAM_COLORS.alpine,
    points: 98,
    wins: 0,
    position: 11,
  },
  {
    id: "driver-12",
    code: "MID",
    name: "Midnight Panther",
    team: "Crystal Williams",
    teamKey: "williams",
    nationality: "American",
    color: TEAM_COLORS.williams,
    points: 72,
    wins: 0,
    position: 13,
  },
  {
    id: "driver-13",
    code: "HAA1",
    name: "Haas Racer One",
    team: "Haas Team",
    teamKey: "haas",
    nationality: "German",
    color: TEAM_COLORS.haas,
    points: 55,
    wins: 0,
    position: 14,
  },
  {
    id: "driver-14",
    code: "HAA2",
    name: "Haas Racer Two",
    team: "Haas Team",
    teamKey: "haas",
    nationality: "American",
    color: TEAM_COLORS.haas,
    points: 48,
    wins: 0,
    position: 15,
  },
  {
    id: "driver-15",
    code: "AUD1",
    name: "Audi Striker",
    team: "Audi F1",
    teamKey: "audi",
    nationality: "German",
    color: TEAM_COLORS.audi,
    points: 60,
    wins: 0,
    position: 16,
  },
  {
    id: "driver-16",
    code: "AUD2",
    name: "Audi Phantom",
    team: "Audi F1",
    teamKey: "audi",
    nationality: "Finnish",
    color: TEAM_COLORS.audi,
    points: 52,
    wins: 0,
    position: 17,
  },
  {
    id: "driver-17",
    code: "CAD1",
    name: "Cadillac Bolt",
    team: "Cadillac Racing",
    teamKey: "cadillac",
    nationality: "American",
    color: TEAM_COLORS.cadillac,
    points: 44,
    wins: 0,
    position: 18,
  },
  {
    id: "driver-18",
    code: "CAD2",
    name: "Cadillac Storm",
    team: "Cadillac Racing",
    teamKey: "cadillac",
    nationality: "Canadian",
    color: TEAM_COLORS.cadillac,
    points: 39,
    wins: 0,
    position: 19,
  },
  {
    id: "driver-19",
    code: "RB1",
    name: "Racing Bull Alpha",
    team: "Racing Bulls",
    teamKey: "rb",
    nationality: "Italian",
    color: TEAM_COLORS.rb,
    points: 67,
    wins: 0,
    position: 20,
  },
  {
    id: "driver-20",
    code: "RB2",
    name: "Racing Bull Beta",
    team: "Racing Bulls",
    teamKey: "rb",
    nationality: "Japanese",
    color: TEAM_COLORS.rb,
    points: 58,
    wins: 0,
    position: 21,
  },
];

function colorForConstructor(constructorId) {
  return TEAM_COLORS[constructorId] || TEAM_COLORS.default;
}

function teamKeyForConstructor(constructorId) {
  return teams[constructorId] ? constructorId : null;
}

export async function fetchDrivers() {
  try {
    const { data } = await axiosInstance.get("/current/driverStandings.json");
    const list =
      data?.MRData?.StandingsTable?.StandingsLists?.[0]?.DriverStandings || [];
    if (!list.length) throw new Error("Empty driver list");

    return list.slice(0, 14).map((entry) => {
      const constructor = entry.Constructors?.[0];
      return {
        id: entry.Driver.driverId,
        code:
          entry.Driver.code ||
          entry.Driver.familyName?.slice(0, 3).toUpperCase(),
        name: `${entry.Driver.givenName} ${entry.Driver.familyName}`,
        team: constructor?.name || "Independent",
        teamKey: teamKeyForConstructor(constructor?.constructorId),
        nationality: entry.Driver.nationality,
        color: colorForConstructor(constructor?.constructorId),
        points: Number(entry.points) || 0,
        wins: Number(entry.wins) || 0,
        position: Number(entry.position) || null,
      };
    });
  } catch (err) {
    console.warn("[f1Api] falling back to mock drivers:", err.message);
    return FALLBACK_DRIVERS;
  }
}
